version: "1"

services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: s339795
      POSTGRES_PASSWORD: FH91Ze1WDQJk6Oed

  backend:
    image: backend
    ports:
      - "8080:21200"